service: file-api
frameworkVersion: '2 || 3'

custom:
  bucket: tommilepola.fi-files
  region: eu-central-1

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  region: ${self:custom.region}
  stage: prod
  httpApi:
    cors:
      allowedOrigins:
        - 'https://tommilepola.fi'
      allowedHeaders:
        - Content-Type
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:GetObject
            - s3:GetObjectAcl
          Resource: "arn:aws:s3:::${self:custom.bucket}/*"

functions:
  getCvUrl:
    handler: handler.getCvUrl
    events:
      - httpApi:
          path: /cv_url
          method: get
    environment:
      BUCKET: ${self:custom.bucket}
      REGION: ${self:custom.region}

plugins:
  - serverless-plugin-typescript