name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: |
          echo Installing dependencies...
          yarn --frozen-lockfile

  build:
    needs: install_dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get node_modules cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Set .env.production
        run: |
          echo Setting .env.production...
          touch .env.production
          echo LAMBDA_ENDPOINT=${{ secrets.LAMBDA_ENDPOINT }} >> .env.production
      - name: Build
        env:
          LAMBDA_ENDPOINT_URL: ${{ secrets.AWS_LAMBDA_URL }}
        run: |
          echo Building...
          yarn build
      - name: Upload /dist artifact
        uses: actions/upload-artifact@v2
        with:
          name: public
          path: |
            public/
            .cache/

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get node_modules cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Download /dist artifact
        uses: actions/download-artifact@v2
        with:
          name: public
      - name: Publish to S3
        env:
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_DEFAULT_REGION: eu-north-1
        run: yarn deploy